[tool.poetry]
name = "vpt_plugin_cellposeSAM"
version = "0.0.11"
description = "CellposeSAM Plugin for VPT"
license = "Apache-2.0"
authors = ["Vizgen <techsupport@vizgen.com>"]
maintainers = ["Ruben Cardenes <ruben.cardenes@vizgen.com>"]
readme = "README.md"
# homepage = ""
repository = "https://github.com/Vizgen/vizgen-postprocessing"
documentation = "https://vizgen.github.io/vizgen-postprocessing/"
# keywords = ""
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
packages = [{ include = "vpt_plugin_cellposesam*", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numba = ">=0.55.2"
numpy = ">=1.24.3"
pandas = ">=2.0.3"
torch = ">=2.0.0, !=2.0.1, !=2.1.0"
vpt_core = ">=1.1.0"
fastremap = "^1.17.7"
fill-voids = "^2.1.1"
natsort = "^8.4.0"
roifile = "2023.5.12"
segment-anything = "^1.0"
torchvision = "0.19.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
opencv-python-headless = ">=4.6.0.66"
flake8 = "^6.0.0"
mypy = "^1.0.0"

[tool.poetry.group.deploy.dependencies]
python-semantic-release = "^7.32.2"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "jfrog"
url = "https://vzartifactory.jfrog.io/artifactory/api/pypi/default-pypi/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = "pyproject.toml:version"
branch = "develop"
changelog_file = "CHANGELOG.md"
build_command = "poetry build"
dist_path = "dist/"
upload_to_release = true
upload_to_pypi = false
remove_dist = false
patch_without_tag = true
